"""Build a copy-paste Jupyter notebook (or .py script) from a dataset + plot picks.

Glue around three existing pieces:
- ``app.standalone_script.standalone_snippet`` for the download cell.
- ``app_cloud.code_annotator.annotate`` for the references block + call-site notes.
- ``app.forms._snippet_map`` / ``_snippet_timeseries`` for plot cells.

The output is shape-checked with ``nbformat`` and ready for download via
``st.download_button``. Cells are deliberately self-contained (each plot
cell re-opens the file) so a learner can run any cell on its own.
"""

from __future__ import annotations

from pathlib import PurePosixPath
from typing import Any

import nbformat as nbf

from app.forms import _snippet_map, _snippet_timeseries
from app_cloud.code_annotator import annotate


# Per-dataset (gridded) dimension hints. We only need these so the plot
# snippets emit `lat` vs `latitude` correctly. If a dataset is missing,
# we fall back to ``("latitude", "longitude", "time")`` and mark the cell
# with a comment telling the user to check ``ds.dims`` if it fails.
_DIM_HINTS: dict[str, tuple[str, str, str]] = {
    "era5-single-levels": ("latitude", "longitude", "valid_time"),
    "era5-pressure-levels": ("latitude", "longitude", "valid_time"),
    "era5-land": ("latitude", "longitude", "valid_time"),
    "era5-daily-stats": ("latitude", "longitude", "valid_time"),
    "earth-data-hub": ("latitude", "longitude", "valid_time"),
    "edh-explorer": ("latitude", "longitude", "valid_time"),
    "arco-era5": ("latitude", "longitude", "time"),
    "cmip6": ("lat", "lon", "time"),
    "esgf-cmip6": ("lat", "lon", "time"),
    "e-obs": ("latitude", "longitude", "time"),
    "c3s-seasonal": ("latitude", "longitude", "forecastMonth"),
    "ecmwf-open-data": ("latitude", "longitude", "step"),
    "hadcrut5": ("latitude", "longitude", "time"),
    "ukcp18": ("grid_latitude", "grid_longitude", "time"),
    "glofas": ("latitude", "longitude", "time"),
}

_GRIDDED_SLUGS = set(_DIM_HINTS.keys())
_TABULAR_SLUGS = {"hadcet", "ghcnd"}

# What plot options each dataset supports.
_PLOT_MENU: dict[str, list[str]] = {
    **{slug: ["map", "timeseries"] for slug in _GRIDDED_SLUGS},
    "hadcet": ["timeseries", "distribution", "rolling_mean"],
    "ghcnd": ["timeseries", "distribution"],
}

# Display labels for plot keys (UI uses these in the multi-select).
PLOT_LABELS: dict[str, str] = {
    "map": "Map (single time step)",
    "timeseries": "Time series (area mean)",
    "distribution": "Distribution histogram",
    "rolling_mean": "Rolling mean",
}


def available_plots(slug: str) -> list[str]:
    """Return the list of plot keys this dataset supports in the builder."""
    return _PLOT_MENU.get(slug, [])


def build_notebook(
    slug: str,
    config: dict[str, Any],
    plot_choices: list[str],
    dataset_name: str,
    dataset_info: str = "",
) -> bytes:
    """Assemble a Jupyter notebook for this dataset + plot choices.

    Returns the raw JSON bytes ready to feed to ``st.download_button``.
    """
    nb = nbf.v4.new_notebook()
    nb["metadata"] = _notebook_metadata()
    nb["cells"] = _notebook_cells(slug, config, plot_choices, dataset_name, dataset_info)
    return nbf.writes(nb).encode("utf-8")


def notebook_preview(
    slug: str,
    config: dict[str, Any],
    plot_choices: list[str],
    dataset_name: str,
    dataset_info: str = "",
) -> list[dict[str, str]]:
    """Return cells as plain dicts so the app can render an inline preview.

    Each entry: ``{"kind": "markdown"|"code", "source": str}``.
    """
    cells = _notebook_cells(slug, config, plot_choices, dataset_name, dataset_info)
    return [
        {"kind": cell["cell_type"], "source": cell["source"]}
        for cell in cells
    ]


def _notebook_cells(
    slug: str,
    config: dict[str, Any],
    plot_choices: list[str],
    dataset_name: str,
    dataset_info: str,
) -> list[Any]:
    """Build the ordered nbformat cell list shared by the bytes and preview paths."""
    cells: list[Any] = []
    cells.append(nbf.v4.new_markdown_cell(_intro_md(dataset_name, dataset_info)))
    cells.append(nbf.v4.new_markdown_cell(_download_intro_md()))
    cells.append(nbf.v4.new_code_cell(annotate(slug, config)))

    for plot_key in plot_choices:
        cell_code = _build_plot_cell(slug, config, plot_key)
        if cell_code is None:
            continue
        cells.append(nbf.v4.new_markdown_cell(_plot_intro_md(plot_key)))
        cells.append(nbf.v4.new_code_cell(cell_code))

    cells.append(nbf.v4.new_markdown_cell(_footer_md(slug, dataset_name)))
    return cells


def build_script(
    slug: str,
    config: dict[str, Any],
    plot_choices: list[str],
    dataset_name: str,
    dataset_info: str = "",
) -> str:
    """Assemble an equivalent single .py file as a string."""
    parts: list[str] = []
    parts.append(f"# {dataset_name}")
    if dataset_info:
        parts.append(f"# {dataset_info}")
    parts.append("# Generated by the climate-data quickstart cloud builder.")
    parts.append("")
    parts.append(annotate(slug, config))
    parts.append("")
    for plot_key in plot_choices:
        cell_code = _build_plot_cell(slug, config, plot_key)
        if cell_code is None:
            continue
        parts.append("\n# " + "-" * 60)
        parts.append(f"# Plot: {PLOT_LABELS.get(plot_key, plot_key)}")
        parts.append("# " + "-" * 60)
        parts.append(cell_code)
    return "\n".join(parts) + "\n"


# ── Cell builders ────────────────────────────────────────────────────


def _build_plot_cell(slug: str, config: dict[str, Any], plot_key: str) -> str | None:
    """Return the source code for one plot cell, or None if unsupported."""
    if slug in _TABULAR_SLUGS:
        return _build_tabular_plot_cell(slug, config, plot_key)
    if slug in _GRIDDED_SLUGS:
        return _build_gridded_plot_cell(slug, config, plot_key)
    return None


def _build_gridded_plot_cell(slug: str, config: dict[str, Any], plot_key: str) -> str | None:
    output_path = _output_path(config)
    open_code = _open_code_gridded(output_path, config)
    var = _guess_var(slug, config)
    lat_dim, lon_dim, time_dim = _DIM_HINTS.get(slug, ("latitude", "longitude", "time"))

    if plot_key == "map":
        return _snippet_map(open_code, var, time_dim, 0)
    if plot_key == "timeseries":
        return _snippet_timeseries(
            open_code, var, time_dim, lat_dim, lon_dim, has_space=True,
        )
    return None


def _build_tabular_plot_cell(slug: str, config: dict[str, Any], plot_key: str) -> str | None:
    output_path = _output_path(config)
    if plot_key == "timeseries":
        return _tabular_timeseries(output_path, slug)
    if plot_key == "distribution":
        return _tabular_distribution(output_path, slug)
    if plot_key == "rolling_mean":
        return _tabular_rolling_mean(output_path, slug)
    return None


# ── Tabular plot snippets (small, parallel structure to forms.py grids) ──


def _tabular_value_col(slug: str) -> str:
    """Best guess for the column to plot. Edit-friendly default."""
    if slug == "hadcet":
        return "temperature_degC"
    if slug == "ghcnd":
        return "TMAX"
    return "value"


def _tabular_timeseries(output_path: str, slug: str) -> str:
    col = _tabular_value_col(slug)
    return (
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n\n"
        f'df = pd.read_csv("{output_path}")\n'
        f'# Adjust the column name below if your file uses a different one.\n'
        f'series = df["{col}"].dropna()\n\n'
        "fig, ax = plt.subplots(figsize=(10, 4))\n"
        "ax.plot(series.values, linewidth=0.7)\n"
        f'ax.set_ylabel("{col}")\n'
        f'ax.set_title("{col} over time")\n'
        "ax.grid(alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
    )


def _tabular_distribution(output_path: str, slug: str) -> str:
    col = _tabular_value_col(slug)
    return (
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n\n"
        f'df = pd.read_csv("{output_path}")\n'
        f'values = df["{col}"].dropna().values\n\n'
        "fig, ax = plt.subplots(figsize=(8, 4))\n"
        "ax.hist(values, bins=50, edgecolor=\"white\", linewidth=0.3)\n"
        f'ax.set_xlabel("{col}")\n'
        'ax.set_ylabel("Count")\n'
        f'ax.set_title("Distribution of {col}")\n'
        "ax.grid(alpha=0.3, axis=\"y\")\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        'print(f"Mean: {values.mean():.3f}, Std: {values.std():.3f}, "\n'
        '      f"Min: {values.min():.3f}, Max: {values.max():.3f}")\n'
    )


def _tabular_rolling_mean(output_path: str, slug: str) -> str:
    col = _tabular_value_col(slug)
    return (
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n\n"
        f'df = pd.read_csv("{output_path}")\n'
        f'series = df["{col}"].dropna()\n'
        "# Window of 30 = ~30 months for HadCET monthly data, or ~30 days for daily.\n"
        "rolling = series.rolling(30, center=True).mean()\n\n"
        "fig, ax = plt.subplots(figsize=(10, 4))\n"
        'ax.plot(series.values, linewidth=0.4, alpha=0.3, label="Raw")\n'
        'ax.plot(rolling.values, linewidth=1.8, label="30-point rolling mean")\n'
        f'ax.set_ylabel("{col}")\n'
        f'ax.set_title("{col} with rolling mean")\n'
        "ax.legend()\n"
        "ax.grid(alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
    )


# ── Helpers ──────────────────────────────────────────────────────────


def _output_path(config: dict[str, Any]) -> str:
    """Construct the path the download cell will write to.

    Returned with forward slashes for cross-platform readability in the
    notebook source. ``None`` filenames (e.g. ESGF, where the canonical
    filename is auto-derived from the search result) fall back to a
    generic placeholder the user can edit.
    """
    out_dir = config.get("output_dir") or "./data"
    out_name = config.get("output_filename") or "output.nc"
    return str(PurePosixPath(out_dir) / out_name)


def _open_code_gridded(output_path: str, config: dict[str, Any]) -> str:
    """Return the appropriate ``xr.open_dataset`` line."""
    if output_path.lower().endswith((".grib", ".grib2", ".grb", ".grb2")):
        return f'ds = xr.open_dataset("{output_path}", engine="cfgrib")'
    return f'ds = xr.open_dataset("{output_path}")'


def _guess_var(slug: str, config: dict[str, Any]) -> str:
    """Best-effort variable name lookup from the form config.

    Each dataset's form uses a different key for "the variable". We try
    the common names in order and fall back to a generic placeholder.
    """
    for key in ("variable", "variable_id", "param", "variables"):
        value = config.get(key)
        if value is None:
            continue
        if isinstance(value, list) and value:
            return value[0]
        if isinstance(value, str):
            return value
    return "data"


def _notebook_metadata() -> dict[str, Any]:
    """Standard metadata so Jupyter, Colab, and VS Code all open it cleanly."""
    return {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10",
        },
    }


# ── Markdown copy ────────────────────────────────────────────────────


def _intro_md(name: str, info: str) -> str:
    parts = [f"# {name}"]
    if info:
        parts.append("")
        parts.append(info)
    parts.append("")
    parts.append(
        "Generated by the climate-data quickstart cloud app. "
        "Each cell is self-contained: run them in order, or pick the "
        "one you want to study and run that on its own."
    )
    return "\n".join(parts)


def _download_intro_md() -> str:
    return (
        "## Download\n\n"
        "The cell below downloads the dataset slice and saves it locally. "
        "The first comment block lists the libraries it uses with links to "
        "their docs."
    )


def _plot_intro_md(plot_key: str) -> str:
    label = PLOT_LABELS.get(plot_key, plot_key.replace("_", " ").title())
    captions = {
        "map": (
            "Spatial map at the first time step. Drag the time index to "
            "step through other timesteps."
        ),
        "timeseries": (
            "Spatially averaged value at each time step. "
            "The simple mean is unweighted; the weighted version accounts "
            "for grid-cell area shrinking towards the poles."
        ),
        "distribution": (
            "Histogram of values. A bell shape is common for temperature; "
            "skew is common for precipitation."
        ),
        "rolling_mean": (
            "A moving average smooths short-term variability to reveal "
            "the underlying trend."
        ),
    }
    body = captions.get(plot_key, "")
    return f"## {label}\n\n{body}".strip()


def _footer_md(slug: str, name: str) -> str:
    return (
        "## Next steps\n\n"
        f"- The full reference for {name} lives at "
        f"`docs/{slug}/README.md` in the climate-data quickstart repo.\n"
        "- To rerun with different parameters, edit the USER CONFIGURATION "
        "block at the top of the download cell.\n"
        "- xarray gallery: https://docs.xarray.dev/en/stable/examples.html\n"
        "- matplotlib gallery: https://matplotlib.org/stable/gallery/index.html"
    )
